[package]
name = "http2-isahc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.7"
chrono = "0.4.22"
opentelemetry = "0.18.0"
opentelemetry-http = "0.7.0"
opentelemetry-jaeger = "0.17.0"
