[package]
name = "http2-isahc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.7"
opentelemetry = "0.18.0"
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-async-std"] }
